openapi: 3.0.3
info:
  title: SD-WAN Service Schema - Test API
  version: 1.0.0
  description: Simple OAS Test API that can be used to test the SD-WAN Service schema validity with OpenAPI Generator tool as well as to generate markdown documentation and plantuml diagrams
paths:
  '/sdWanUni':
    get:
      operationId: sdWanUni
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: 'sdWanUni.yaml'
  '/sdWanVc':
    get:
      operationId: sdWanVc
      responses:
        '200':
          description: Ok
          content:
            application/json;charset=utf-8:
              schema:
                type: array
                items:
                  $ref: 'sdWanVc.yaml'
  